### ISSUE TITLE
Check for error in Lora packet status

### ISSUE THREAD

**Issue by Xeenych** [Lora-net/SWDR005#1]
According to errata 16.2

Here we must read error byte to check it for CRC error:
https://github.com/Lora-net/SWDR005/blob/f9181c1c84ec5ff6d66bfa6085321505b8d281de/src/sx128x.h#L873

**Comment by opeyrard** [comment]
This situation is described in the errata 16.3 of the datasheet.
There is no code update requested.
Issue can be closed.
